CREATE DATABASE STUDENT;
USE STUDENT;
CREATE TABLE TABLE_USER
(
	USER_ID INT NOT NULL AUTO_INCREMENT,
    USER_NAME VARCHAR(20),
    USER_PASSWORD VARCHAR(20),
    PRIMARY KEY(USER_ID)
);

CREATE TABLE STUDENT
(
	STUDENT_ID INT NOT NULL AUTO_INCREMENT,
    STUDENT_NAME VARCHAR(100),
    STUDENT_CODE VARCHAR(50),
    PRIMARY KEY(STUDENT_ID)
);

CREATE TABLE STUDENT_INFO
(
	INFO_ID INT NOT NULL AUTO_INCREMENT,
    STUDENT_ID INT,
    ADDRESS VARCHAR(200),
    AVERAGE_SCORE DOUBLE,
    DATE_OF_BIRTH DATE,
    PRIMARY KEY(INFO_ID),
    FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(STUDENT_ID)
);